/*
     +---------------------+
     |                     |
     |                     |
     |                     |
     |                     |
     |           1         |
     |                     |
     |                     |
     |                     |
     |                     |
     |                     |
     +---------------------+
*/

const layout_desc_1 layout_1 PROGMEM =
{
	//number of active widgets
	1,
	//position of widgets
	{
		//x, y, w, h
		{0, 0, 78, 48},
	}
};
