/*
   +---------+ +---------+
   |         | |         |
   |         | |         |
   |         | |         |
   |    1    | |    2    |
   |         | |         |
   |         | |         |
   |         | |         |
   +---------+ +---------+
*/

const layout_desc_2 layout_11 PROGMEM =
{
	//number of active widgets
	2,
	//position of widgets
	{
		//x, y, w, h
		{0, 0, 39, 48},
		{39, 0, 39, 48},
	}
};
