/*
   +--------+ +--------+
   |    1   | |    2   |
   +--------+ +--------+
   +-------------------+
   |   	       	       |
   |         3 	       |
   |                   |
   |                   |
   +-------------------+
*/

const layout_desc_3 layout_21 PROGMEM =
{
	//number of active widgets
	3,
	//position of widgets
	{
		//x, y, w, h
		{0, 0, 39, 16},
		{39, 0, 39, 16},
		{0, 16, 78, 32},
	}
};



